### PR TITLE
Removed unwanted use of variable access_token.

### PR DESCRIPTION
**Pull request by unnikrishnan-r**
`
const access_token = data.access_token            
makeamadeusApiCall(access_token, queryString);
`
was changed to 

`makeamadeusApiCall(data.access_token, queryString);
`

### CODE REVIEW

**Comment by unnikrishnan-r** [comment]
@SarneetGit @ManjyotThandi  Please review when you get a chance.
2 commits in this PR:
1. Simple change to remove a unwanted variable
2. Handles the return of the function a little better. Please look at the sample calls to understand it a little better. Unfortunately the formatting extension was messed up earlier and hence it shows a lot of lines as changed.

**Review by SarneetGit — COMMENTED** [review]
Parsed through changes, they look good to me. No additional comments.

**Review by SarneetGit — APPROVED** [review]
Forgot to approve lol.

**Comment by SarneetGit** [comment]
I will let you merge Unni.

**Comment by unnikrishnan-r** [comment]
Reopening the PR because it was closed without merging to master

**Pull request merged**
